# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 06:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(max_length=100)),
                ('sub_description', models.CharField(max_length=100)),
                ('sub_due_date', models.DateTimeField(default=datetime.datetime.now)),
                ('sub_state', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('due_date', models.DateTimeField(default=datetime.datetime.now)),
                ('state', models.IntegerField(default=0)),
                ('sub_task_many', models.ManyToManyField(related_name='sub_tasks', to='tasks.SubTask')),
            ],
        ),
    ]
