# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='sub_task_many',
            field=models.ManyToManyField(blank=True, null=True, related_name='sub_tasks', to='tasks.SubTask'),
        ),
    ]
